// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADu887M4YkehNrn-iKE8mi2VLDhNDns5E',
    appId: '1:997752335330:web:f787a65871c03c19eb27bb',
    messagingSenderId: '997752335330',
    projectId: 'walkpenang-5cefb',
    authDomain: 'walkpenang-5cefb.firebaseapp.com',
    storageBucket: 'walkpenang-5cefb.firebasestorage.app',
    measurementId: 'G-52X21LTPY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpqJ21IDIF60KJiclTqw0nPzix0zLVh-U',
    appId: '1:997752335330:android:8f0666466ee06535eb27bb',
    messagingSenderId: '997752335330',
    projectId: 'walkpenang-5cefb',
    storageBucket: 'walkpenang-5cefb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm3Q5CV-MDdXyGFx_SgrQfa7h2Gb7HVXY',
    appId: '1:997752335330:ios:75de6683dacc97cceb27bb',
    messagingSenderId: '997752335330',
    projectId: 'walkpenang-5cefb',
    storageBucket: 'walkpenang-5cefb.firebasestorage.app',
    iosClientId: '997752335330-cn23bbhc9qj1p77fd61ujnp0g8q0ahv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.walkpenang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm3Q5CV-MDdXyGFx_SgrQfa7h2Gb7HVXY',
    appId: '1:997752335330:ios:75de6683dacc97cceb27bb',
    messagingSenderId: '997752335330',
    projectId: 'walkpenang-5cefb',
    storageBucket: 'walkpenang-5cefb.firebasestorage.app',
    iosClientId: '997752335330-cn23bbhc9qj1p77fd61ujnp0g8q0ahv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.walkpenang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADu887M4YkehNrn-iKE8mi2VLDhNDns5E',
    appId: '1:997752335330:web:b1a990f5c63c019eeb27bb',
    messagingSenderId: '997752335330',
    projectId: 'walkpenang-5cefb',
    authDomain: 'walkpenang-5cefb.firebaseapp.com',
    storageBucket: 'walkpenang-5cefb.firebasestorage.app',
    measurementId: 'G-DSGQ21KGM5',
  );
}
